Enable Python SyntaxError checks, move to Python 3
* Enable Flake8 check for SyntaxError: invalid syntax.
* Fix syntax errors and move remaining code from Python 2 to Python 3.
* Remove experimental newgui (completely replaced by the single window project).
* Remove duplicate global ignore lines for Flake8 F811 (redefinition of unused).
* Replace global ignore of Flake8 W605 (invalid escape sequence) by per-file ignores.
* Define underscore as buildin as in core.
* Add per-file ignores for F823 for boxplot code due to use of _ as unused.
* Add exclude directories as in core.
* Remove prints which are clearly debug-only (instead of updating to Python 3).
* Fix typos in or close to modified code.