r.houghtransform: no namespace for extern functions
Avoids compilation error with clang 3.8.0 and g++.
Namespace for C functions creates some confusion leading to
* conflicting types for sigsetjmp (clang)
* no member named size_t in namespace grass::std; did you mean ::std::size_t (clang)
* grass::std::size_t has not been declared (g++)
* error: ::max_align_t has not been declared (g++)


git-svn-id: https://svn.osgeo.org/grass/grass-addons@73078 15284696-431f-4ddb-bdfa-cd5b030d7da7