v.nnstat: fix bool compilation error
Attempt to fix compilation error:

```
make
...
                 from mbb.c:1:
mbb.h:9:32: error: expected ‘;’, identifier or ‘(’ before ‘_Bool’
    9 | typedef enum { BFALSE, BTRUE } bool;
      |                                ^~~~
compilation terminated due to -Wfatal-errors.
```